@extends('admin.layouts.app')
@section('content')
<div class="card shadow-sm"><div class="card-body"><h4 class="mb-4">Create Blog Post</h4>
<form method="POST" action="{{ route('admin.blog.posts.store') }}" enctype="multipart/form-data">@csrf
<div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input type="text" name="title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draft</option><option value="published">Published</option></select></div>
<div class="col-md-6"><label class="form-label">Category</label><div class="input-group"><select id="category_id" name="category_id" class="form-select"><option value="">Select Category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><button type="button" class="btn btn-outline-primary" id="add-category">+ Add Category</button></div></div>
<div class="col-md-6"><label class="form-label">Publish Date</label><input type="datetime-local" name="published_at" class="form-control"></div><div class="col-md-6"><label class="form-label">Slug</label><input type="text" name="slug" class="form-control"></div><div class="col-md-6"><label class="form-label">Featured Image</label><input type="file" name="image" class="form-control"></div>
<div class="col-md-6"><label class="form-label">Image Alt Text</label><input type="text" name="image_alt_text" class="form-control"></div><div class="col-md-6"><label class="form-label">Image Title</label><input type="text" name="image_title" class="form-control"></div><div class="col-md-6"><label class="form-label">Image Caption</label><input type="text" name="image_caption" class="form-control"></div><div class="col-12"><label class="form-label">Image Description</label><textarea name="image_description" class="form-control" rows="2"></textarea></div>
<div class="col-12"><label class="form-label">Excerpt</label><textarea name="excerpt" class="form-control" rows="2"></textarea></div><div class="col-12"><label class="form-label">Content</label><textarea name="content" id="blog-editor"></textarea></div></div><button class="btn btn-primary mt-4">Save Post</button></form></div></div>
@endsection
@push('scripts')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{tinymce.init({selector:'#blog-editor',height:550,plugins:'lists link image table autoresize',toolbar:'undo redo | blocks | bold italic underline | alignleft aligncenter alignright | bullist numlist | blockquote | link image table',menubar:false,branding:false,block_formats:'Paragraph=p;Heading 2=h2;Heading 3=h3;Heading 4=h4'});document.getElementById('add-category').addEventListener('click',async()=>{const name=prompt('Category name');if(!name)return;const r=await fetch('{{ route('admin.blog.categories.quick') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'},body:JSON.stringify({name})});if(!r.ok){alert('Unable to create category.');return;}const c=await r.json(),s=document.getElementById('category_id');s.add(new Option(c.name,c.id,true,true));s.value=c.id;});});</script>
@endpush
